//! Layer 1 — Bytes generators.
//!
//! How raw bytes per item are generated. Implementations live here;
//! this file is the scaffold + variant enumeration.
//!
//! Phase coverage:
//!
//! - **#236 next:** [`BytesLayer::BitFlipVariants`] — clustering-fuzz
//!   primitive (M seed clusters × N variants at bit-flip probability p).
//! - **#236:** [`BytesLayer::UniformRandom`] — ChaCha8 byte stream.
//! - **Later:** [`BytesLayer::MarkovChain`], [`BytesLayer::ByteHistogramTargeted`].

use crate::ClusterId;

/// One of the four byte-generation strategies.
#[derive(Debug, Clone)]
pub enum BytesLayer {
    /// Uniform-random bytes from ChaCha8. No cluster structure.
    /// Use when testing throughput on unstructured input.
    UniformRandom {
        /// Number of bytes per item.
        bytes_per_item: usize,
    },
    /// **Clustering-fuzz primitive.** M seed clusters; each item is a
    /// variant of one seed with each bit independently flipped at
    /// probability `p_flip`. By construction, variants of seed_i are
    /// closer to each other than to variants of seed_j (per
    /// `docs/hnsw/components/CLUSTERING_FUZZ.md`).
    BitFlipVariants {
        /// Bytes per seed (and per variant).
        bytes_per_item: usize,
        /// Number of seed clusters.
        clusters: usize,
        /// Variants per seed cluster. Total item count = `clusters * variants_per_cluster`.
        variants_per_cluster: usize,
        /// Per-bit flip probability ∈ [0.0, 1.0]. Typical clustering-
        /// fuzz sweet spot is 0.05–0.20.
        p_flip: f32,
    },
    /// Byte stream produced by an order-N Markov chain. Models
    /// text-like distributions with controllable entropy.
    /// **Not implemented yet** (#238 work).
    MarkovChain {
        /// Bytes per item.
        bytes_per_item: usize,
        /// Markov chain order (1 = bigram, 2 = trigram, ...).
        order: u8,
        /// Independent seed for the transition table.
        transition_seed: u64,
    },
    /// Bytes generated to match an empirical byte-histogram (e.g. from
    /// the F22 paper's calibration corpus). **Not implemented yet** (#238).
    ByteHistogramTargeted {
        /// Bytes per item.
        bytes_per_item: usize,
        /// 256-entry probability vector summing to 1.0.
        histogram: Box<[f32; 256]>,
    },
}

impl BytesLayer {
    /// Bytes per generated item (constant per spec).
    pub fn bytes_per_item(&self) -> usize {
        match self {
            BytesLayer::UniformRandom { bytes_per_item, .. }
            | BytesLayer::BitFlipVariants { bytes_per_item, .. }
            | BytesLayer::MarkovChain { bytes_per_item, .. }
            | BytesLayer::ByteHistogramTargeted { bytes_per_item, .. } => *bytes_per_item,
        }
    }

    /// Total item count this layer will generate, given the spec's
    /// `n_items`. Some layers (e.g. `BitFlipVariants`) override
    /// `n_items` based on their own parameters.
    pub fn item_count(&self, n_items: usize) -> usize {
        match self {
            BytesLayer::BitFlipVariants {
                clusters,
                variants_per_cluster,
                ..
            } => clusters * variants_per_cluster,
            _ => n_items,
        }
    }
}

/// One generated byte sequence with its constructed cluster label
/// (if the layer produces clusters).
#[derive(Debug, Clone)]
pub struct GeneratedBytes {
    /// Raw bytes for this item.
    pub bytes: Vec<u8>,
    /// Cluster membership, if the layer assigns one. `None` for
    /// uniform-random / Markov / byte-histogram.
    pub cluster_id: Option<ClusterId>,
}
